### ISSUE TITLE
Click twice

### ISSUE THREAD

**Issue by Dan-True** [mperator/vue-anchor-router-link#1]
I've inserted some anchor routers links on my page:

**my html file:**
```
<anchor-router-link :to="{hash: '#step1'}">
    Step 1. - Admin Interface 
</anchor-router-link>
```

**boot.ts:**
```
import VueAnchorRouterLink from 'vue-anchor-router-link';
Vue.component('anchor-router-link', VueAnchorRouterLink)
```

This sets the route correctly:

http://localhost:51557/plugins-woocommerce#step0

But I need to click the anchor link twice before it correctly scrolls to the div with Id = #step1.  At the second click everything works as intended.

Any ideas on what I'm doing wrong?

**Comment by Dan-True** [comment]
Direct anchor link doesn't work either. If I hit the link above directly, I'm just stuck at the top of page.

**Comment by mperator** [comment]
> But I need to click the anchor link twice before it correctly scrolls to the div with Id = #step1. At the second click everything works as intended.
> 
> Any ideas on what I'm doing wrong?

Your problem sounds like you have not set the scrollBehavior of the router itself. Make sure to use the same options like in the anchro-router-link.

The anchor-router-link works only in addition to the router scrollBehavior and addresses the one case when the router scrollBehavior will not work as expected (at least for my expectations). That is if the route has not changed and you want to scroll to the same anchor point again. The router scrollBehavior is only be triggered if the route has changed. In my example I scrolled to the anchor point any-link.html#test then I scrolled to an other part of the site. In the address bar you will see still the same active anchor point any-link.html#test even if you changed the position of the site. Now if you want to jump back to the same anchor point #test it won't work because the route has not changed. For that you can use the anchor-router-link. In the condition you mentioned before the anchor-router-link checks if an routing was triggered and the route is the same. Then it will manually start the scrolling to the point.

> In my view this condition should either be removed or it should remove the hash from each side of the comparison. What is the intent behind the condition?

If we remove the condition the router point behaves like the router does at the time I wrote the anchor-router-point. If your project does not have the apart which needs to scroll to the same anchor point twice I suggest to use the standard scrollBehavior of the vue-router https://router.vuejs.org/guide/advanced/scroll-behavior.html. This will work totally fine. 

I know my answer is quite late but I hope I could make things more clear. I will do some research if router still does have the same behavior and if the anchor-router-link is needed anymore.

**Comment by gr3w2** [comment]
I was facing the same problem, and adding just `scrollBehavior` did not help me, because `scrollBehavior` is executed before opening a page with the desired element hash which will be used as an anchor. So I added kinda dirty hack and everything working properly (even with smooth animation 🤟):
```js
scrollBehavior(to, from, savedPosition) {
    if (to.hash) {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          VueScrollTo.scrollTo(to.hash, 700);
          resolve({ selector: to.hash });
        }, 500);
      });
    } else if (savedPosition) {
      return savedPosition;
    } else {
      return { x: 0, y: 0 };
    }
  }
```
Long story short, this 500ms timeout gives time to open a page with the desired anchor, and only after that it will scroll a page to the anchor
